spring.datasource.url=${JDBC_DATABASE_URL:${DATABASE_URL:jdbc:postgresql://localhost:5432/sportsbooking}}
spring.datasource.username=${JDBC_DATABASE_USERNAME:${DATABASE_USERNAME:postgres}}
spring.datasource.password=${JDBC_DATABASE_PASSWORD:${DATABASE_PASSWORD:postgres}}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true